lib/package.json, pnpm-lock.yaml
=> fix: lockfile

lib/src/flagsClient.test.ts, lib/src/getFrontendFlags.test.ts, lib/src/utils.test.ts
I added some tests while experimenting with CLI
=> More unit tests

lib/package.json, lib/src/cli/helpers.test.ts, lib/src/cli/helpers.ts, lib/src/getDefinitions.ts
Moved from https://github.com/Unleash/unleash-client-nextjs/pull/27
=> Possibility to add instance_id and omit token #27

lib/package.json, lib/src/getFrontendFlags.test.ts, lib/src/getFrontendFlags.ts
=> reject promise when unleash client fails to fetch

lib/src/getDefinitions.test.ts, lib/src/getDefinitions.ts
Save data transfer when working with segments.
=> Add client spec header

README.md
Documentation for feature that is in pre-release.
closes https://github.com/Unleash/unleash-client-nextjs/issues/21
=> Add instance id to the docs

.github/workflows/release.yml, lib/package.json
Fix build - postinstall also tries to run locally after installing the package
=> fix: prebuild script

.github/workflows/release.yml, package.json
From my local experiments it looks like removing this field will allow for pnpm and yarn to co-exist after a breaking change in yarn 1.22.21 that got automatically installed on GH agents.
=> chore: remove package manager from package json

lib/package.json, pnpm-lock.yaml
Closes #64 
Unleash Client 5.5.1 upgrades the vulnerable ip@2.0.0 package
=> fix: Upgrade vulnerable IP package

lib/package.json, lib/src/core/client/strategy/strategy.ts, lib/src/core/variant.ts, pnpm-lock.yaml
Update to match latest client specification.
Closes #69
=> fix: variant stickiness

lib/package.json, pnpm-lock.yaml
This version bump contains abort controller fix: https://github.com/Unleash/unleash-proxy-client-js/pull/207
=> chore: update js client and react client deps

.gitignore, lib/package.json, lib/src/flagsClient.ts, pnpm-lock.yaml
- Remove errors for undefined fetch and AbortController in middeware
- Update dependencies
Closes https://github.com/Unleash/unleash-client-nextjs/issues/76
`lib/src/flagsClient.ts`
=> Fix: prevent middleware log errors

example/package.json, lib/package.json, package.json, yarn.lock
Update Unleash React SDK to get the latest features
=> chore: update dependencies

README.md
As requested in #83 - This PR adds a line about using Edge and points out what kind of token you need.
=> docs: Add line about using Edge

README.md
=> docs: ssr metrics

README.md, example/src/middleware.ts
Describe metrics in middleware.
=> docs: middleware metrics

README.md
Update docs before 1.5.0 release
=> docs: 1.5.0

lib/src/flagsClient.test.ts, lib/src/flagsClient.ts, lib/src/utils.ts, yarn.lock
Allow passing of custom clientKey, appName & url into the flagsClient instead of relying on env variables
=> feat: flagsClient custom config

example/src/pages/ssr.tsx, lib/package.json, lib/src/evaluateFlags.test.ts, lib/src/flagsClient.test.ts, lib/src/getDefinitions.test.ts, lib/src/getDefinitions.ts, lib/vitest.config.ts, yarn.lock
- update upstream Unleash dependencies
- make sure standard Unleash identification headers are sent
- updated tests
=> fix: update identification headers

lib/package.json, lib/src/flagsClient.test.ts, yarn.lock
Bump `unleash-proxy-client`
Closes #106
=> fix: flagsClient returning "disabled" state after multiple asynchronous calls
